name: factory

services:
  postgres:
    image: postgres:14
    container_name: postgres
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./volumes/postgres/shm:/dev/shm
    environment:
      POSTGRES_DB: factory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sLOMATIpHEAs
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - backend
    ports:
      - 5432:5432

  neo4j:
    image: neo4j:5.13.0
    container_name: neo4j
    volumes:
      - ./volumes/neo4j/data:/data
      - ./volumes/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/sLOMATIpHEAs
      - NEO4J_PLUGINS=["apoc"]
    networks:
      - backend
    ports:
      - 7474:7474
      - 7687:7687
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G

  mongo:
    image: mongo:5.0.26
    container_name: mongo
    volumes:
      - ./volumes/mongo:/data/db
    networks:
      - backend
    ports:
      - 27017:27017

networks:
  backend:
